[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "myTestProject"
authors = [{name = "Brooklyn", email = "brooklyn@brooklyn.com"}]
dynamic = ["version =0x", "description=some junk project with no meaning"]
